function PHI = single_H_function(in1)
%single_H_function
%    PHI = single_H_function(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    12-Oct-2023 16:47:44

p_r_x = in1(:,1);
p_r_y = in1(:,2);
p_r_z = in1(:,3);
PHI = [p_r_x.^2;p_r_x.*p_r_y.*2.0;p_r_x.*p_r_z.*2.0;p_r_y.^2;p_r_y.*p_r_z.*2.0;p_r_z.^2;p_r_x.*-2.0;p_r_y.*-2.0;p_r_z.*-2.0;1.0];
