function out1 = single_Y_function(in1,in2,in3,in4,m,w_noise)
%single_Y_function
%    OUT1 = single_Y_function(IN1,IN2,IN3,IN4,M,W_NOISE)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    12-Oct-2023 16:47:46

a = in3(:,1);
b = in3(:,2);
m_11 = in4(:,1);
m_12 = in4(:,2);
m_13 = in4(:,3);
m_22 = in4(:,4);
m_23 = in4(:,5);
m_33 = in4(:,6);
p_r_x_1 = in1(:,1);
p_r_y_1 = in1(:,2);
p_r_z_1 = in1(:,3);
p_t_x = in2(1,:);
p_t_y = in2(2,:);
p_t_z = in2(3,:);
t2 = a.^2;
t3 = b.^2;
t4 = -p_t_x;
t5 = -p_t_y;
t6 = -p_t_z;
t7 = p_r_x_1+t4;
t8 = p_r_y_1+t5;
t9 = p_r_z_1+t6;
t10 = t7.^2;
t11 = t8.^2;
t12 = t9.^2;
t13 = t10+t11+t12;
t14 = 1.0./t13;
out1 = -t13.*(-1.0./(t10.*t14.*3.0+1.0).^(1.0./3.0)+(t10.*t14-1.0)./t3+(t10.*t14)./t2)+m_11.*p_r_x_1.^2+m_22.*p_r_y_1.^2+m_33.*p_r_z_1.^2+p_t_x.^2.*t3+p_t_y.^2.*t2+p_t_z.^2.*t2+m_12.*p_r_x_1.*p_r_y_1.*2.0+m_13.*p_r_x_1.*p_r_z_1.*2.0+m_23.*p_r_y_1.*p_r_z_1.*2.0-p_r_x_1.*p_t_x.*t3.*2.0-p_r_y_1.*p_t_y.*t2.*2.0-p_r_z_1.*p_t_z.*t2.*2.0+(2.0.^(2.0./3.0).*m.^(2.0./3.0).*t2.*t3.*t13.^(5.0./2.0).*w_noise.*1.0./pi.^(2.0./3.0))./4.0;
