function pos_acc = compute_pos_acc(in1,in2)
%COMPUTE_POS_ACC
%    POS_ACC = COMPUTE_POS_ACC(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    04-Nov-2023 16:09:19

T = in1(13,:);
g = in2(:,7);
m = in2(:,6);
phi = in1(10,:);
psi = in1(12,:);
theta = in1(11,:);
t2 = cos(phi);
t3 = cos(psi);
t4 = sin(phi);
t5 = sin(psi);
t6 = sin(theta);
t7 = 1.0./m;
pos_acc = [T.*t7.*(t4.*t5+t2.*t3.*t6);-T.*t7.*(t3.*t4-t2.*t5.*t6);-t7.*(g.*m-T.*t2.*cos(theta))];
