function pos_jerk = compute_pos_jerk(in1,in2)
%COMPUTE_POS_JERK
%    POS_JERK = COMPUTE_POS_JERK(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    04-Nov-2023 16:09:19

T = in1(13,:);
Tdot = in1(14,:);
m = in2(:,6);
p = in1(7,:);
phi = in1(10,:);
psi = in1(12,:);
q = in1(8,:);
r = in1(9,:);
theta = in1(11,:);
t2 = cos(phi);
t3 = cos(psi);
t4 = cos(theta);
t5 = sin(phi);
t6 = sin(psi);
t7 = sin(theta);
t13 = 1.0./m;
t8 = q.*t2;
t9 = r.*t2;
t10 = p.*t4;
t11 = q.*t5;
t12 = r.*t5;
t14 = t3.*t5;
t15 = t5.*t6;
t16 = 1.0./t4;
t20 = t2.*t3.*t7;
t21 = t2.*t6.*t7;
t17 = t7.*t9;
t18 = t7.*t11;
t19 = -t12;
t22 = t9+t11;
t23 = -t21;
t25 = t15+t20;
t24 = t8+t19;
t26 = t14+t23;
t27 = t10+t17+t18;
pos_jerk = [Tdot.*t13.*t25+T.*t13.*t16.*t22.*t26+T.*t13.*t16.*t27.*(t2.*t6-t7.*t14)+T.*t2.*t3.*t4.*t13.*t24;-Tdot.*t13.*t26+T.*t13.*t16.*t22.*t25-T.*t13.*t16.*t27.*(t2.*t3+t7.*t15)+T.*t2.*t4.*t6.*t13.*t24;-t13.*(T.*q.*t7+T.*t5.*t10-Tdot.*t2.*t4)];
