function input_mapping = input_mapping(in1,in2)
%INPUT_MAPPING
%    INPUT_MAPPING = INPUT_MAPPING(IN1,IN2)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    04-Nov-2023 16:09:18

T = in1(1,:);
a = in2(:,1);
b = in2(:,2);
rD = in2(:,9);
rT = in2(:,8);
tau_phi = in1(2,:);
tau_psi = in1(4,:);
tau_theta = in1(3,:);
t2 = 1.0./a;
t3 = 1.0./b;
t4 = 1.0./rD;
t5 = T./4.0;
t6 = (t2.*tau_phi)./2.0;
t7 = (t3.*tau_theta)./2.0;
t8 = (rT.*t4.*tau_psi)./4.0;
t9 = -t6;
t10 = -t7;
t11 = -t8;
input_mapping = [t5+t6+t10+t11;t5+t6+t7+t8;t5+t7+t9+t11;t5+t8+t9+t10];
