function TM = inv_input_mapping_matrix(in1)
%INV_INPUT_MAPPING_MATRIX
%    TM = INV_INPUT_MAPPING_MATRIX(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    04-Nov-2023 16:09:19

a = in1(:,1);
b = in1(:,2);
rD = in1(:,9);
rT = in1(:,8);
t2 = 1.0./rT;
t3 = a./2.0;
t4 = b./2.0;
t5 = rD.*t2;
t6 = -t3;
t7 = -t4;
t8 = -t5;
TM = reshape([1.0,t3,t7,t8,1.0,t3,t4,t5,1.0,t6,t4,t8,1.0,t6,t7,t5],[4,4]);
