function om = om(in1)
%OM
%    OM = OM(IN1)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    04-Nov-2023 12:22:02

p = in1(1,:);
phi = in1(4,:);
q = in1(2,:);
r = in1(3,:);
theta = in1(5,:);
om = [(p.*cos(theta)+r.*cos(phi).*sin(theta)+q.*sin(phi).*sin(theta))./cos(theta);q.*cos(phi)-r.*sin(phi);(r.*cos(phi)+q.*sin(phi))./cos(theta)];
