function [J_f_x,J_f_u] = quadrotor_model_jac(in1,in2,neigh_pos,N_neighbours,non_neigh_pos,N_non_neighbours,d_safe,v_max,in9)
%QUADROTOR_MODEL_JAC
%    [J_f_x,J_f_u] = QUADROTOR_MODEL_JAC(IN1,IN2,NEIGH_POS,N_neighbours,NON_NEIGH_POS,N_non_neighbours,D_SAFE,V_MAX,IN9)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    10-Nov-2023 16:09:33

Jxx = in9(:,3);
Jyy = in9(:,4);
Jzz = in9(:,5);
T1 = in2(1,:);
T2 = in2(2,:);
T3 = in2(3,:);
T4 = in2(4,:);
a = in9(:,1);
b = in9(:,2);
m = in9(:,6);
p = in1(7,:);
phi = in1(10,:);
psi = in1(12,:);
q = in1(8,:);
r = in1(9,:);
rD = in9(:,9);
rT = in9(:,8);
theta = in1(11,:);
mt1 = [0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-(r.*(Jxx-Jzz))./Jyy,(q.*(Jxx-Jyy))./Jzz,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,(r.*(Jyy-Jzz))./Jxx,0.0,(p.*(Jxx-Jyy))./Jzz,(sin(phi).*sin(theta))./cos(theta),cos(phi),sin(phi)./cos(theta),0.0,0.0,0.0,0.0,0.0,0.0,(q.*(Jyy-Jzz))./Jxx,-(p.*(Jxx-Jzz))./Jyy,0.0];
mt2 = [(cos(phi).*sin(theta))./cos(theta),-sin(phi),cos(phi)./cos(theta),0.0,0.0,0.0,((cos(phi).*sin(psi)-cos(psi).*sin(phi).*sin(theta)).*(T1+T2+T3+T4))./m,-((cos(phi).*cos(psi)+sin(phi).*sin(psi).*sin(theta)).*(T1+T2+T3+T4))./m,-(cos(theta).*sin(phi).*(T1+T2+T3+T4))./m,0.0,0.0,0.0,(q.*cos(phi).*sin(theta)-r.*sin(phi).*sin(theta))./cos(theta),-r.*cos(phi)-q.*sin(phi),(q.*cos(phi)-r.*sin(phi))./cos(theta),0.0,0.0,0.0,(cos(phi).*cos(psi).*cos(theta).*(T1+T2+T3+T4))./m,(cos(phi).*cos(theta).*sin(psi).*(T1+T2+T3+T4))./m,-(cos(phi).*sin(theta).*(T1+T2+T3+T4))./m,0.0,0.0,0.0];
mt3 = [(-p.*sin(theta)+r.*cos(phi).*cos(theta)+q.*cos(theta).*sin(phi))./cos(theta)+1.0./cos(theta).^2.*sin(theta).*(p.*cos(theta)+r.*cos(phi).*sin(theta)+q.*sin(phi).*sin(theta)),0.0,1.0./cos(theta).^2.*sin(theta).*(r.*cos(phi)+q.*sin(phi)),0.0,0.0,0.0,((cos(psi).*sin(phi)-cos(phi).*sin(psi).*sin(theta)).*(T1+T2+T3+T4))./m,((sin(phi).*sin(psi)+cos(phi).*cos(psi).*sin(theta)).*(T1+T2+T3+T4))./m,0.0,0.0,0.0,0.0,0.0,0.0,0.0];
J_f_x = reshape([mt1,mt2,mt3],12,12);
if nargout > 1
    mt4 = [0.0,0.0,0.0,(sin(phi).*sin(psi)+cos(phi).*cos(psi).*sin(theta))./m,-(cos(psi).*sin(phi)-cos(phi).*sin(psi).*sin(theta))./m,(cos(phi).*cos(theta))./m,a./(Jxx.*2.0),(b.*(-1.0./2.0))./Jyy,-rD./(Jzz.*rT),0.0,0.0,0.0,0.0,0.0,0.0,(sin(phi).*sin(psi)+cos(phi).*cos(psi).*sin(theta))./m,-(cos(psi).*sin(phi)-cos(phi).*sin(psi).*sin(theta))./m,(cos(phi).*cos(theta))./m,a./(Jxx.*2.0),b./(Jyy.*2.0),rD./(Jzz.*rT),0.0,0.0,0.0,0.0,0.0,0.0,(sin(phi).*sin(psi)+cos(phi).*cos(psi).*sin(theta))./m];
    mt5 = [-(cos(psi).*sin(phi)-cos(phi).*sin(psi).*sin(theta))./m,(cos(phi).*cos(theta))./m,(a.*(-1.0./2.0))./Jxx,b./(Jyy.*2.0),-rD./(Jzz.*rT),0.0,0.0,0.0,0.0,0.0,0.0,(sin(phi).*sin(psi)+cos(phi).*cos(psi).*sin(theta))./m,-(cos(psi).*sin(phi)-cos(phi).*sin(psi).*sin(theta))./m,(cos(phi).*cos(theta))./m,(a.*(-1.0./2.0))./Jxx,(b.*(-1.0./2.0))./Jyy,rD./(Jzz.*rT),0.0,0.0,0.0];
    J_f_u = reshape([mt4,mt5],12,4);
end
