function [J_y_x,J_y_u] = quadrotor_output_jac(in1,in2,neigh_pos,N_neighbours,non_neigh_pos,N_non_neighbours,d_safe,v_max,in9)
%QUADROTOR_OUTPUT_JAC
%    [J_y_x,J_y_u] = QUADROTOR_OUTPUT_JAC(IN1,IN2,NEIGH_POS,N_neighbours,NON_NEIGH_POS,N_non_neighbours,D_SAFE,V_MAX,IN9)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    10-Nov-2023 16:09:33

J_y_x = reshape([1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0],[4,12]);
if nargout > 1
    J_y_u = reshape([0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0],[4,4]);
end
