function quadrotor_model_y = quadrotor_output(in1,in2,neigh_pos,N_neighbours,non_neigh_pos,N_non_neighbours,d_safe,v_max,in9)
%QUADROTOR_OUTPUT
%    QUADROTOR_MODEL_Y = QUADROTOR_OUTPUT(IN1,IN2,NEIGH_POS,N_neighbours,NON_NEIGH_POS,N_non_neighbours,D_SAFE,V_MAX,IN9)

%    This function was generated by the Symbolic Math Toolbox version 9.2.
%    04-Nov-2023 12:22:03

psi = in1(12,:);
x = in1(1,:);
y = in1(2,:);
z = in1(3,:);
quadrotor_model_y = [x;y;z;psi];
